In [3]:
import pandas as pd

df = pd.read_csv("twcs.csv")

# load the dataset

In [4]:
print(df.head(5))

#chek the type of the data

   tweet_id   author_id  inbound                      created_at  \
0         1  sprintcare    False  Tue Oct 31 22:10:47 +0000 2017
1         2      115712     True  Tue Oct 31 22:11:45 +0000 2017
2         3      115712     True  Tue Oct 31 22:08:27 +0000 2017
3         4  sprintcare    False  Tue Oct 31 21:54:49 +0000 2017
4         5      115712     True  Tue Oct 31 21:49:35 +0000 2017

                                                text response_tweet_id  \
0  @115712 I understand. I would like to assist y...                 2
1      @sprintcare and how do you propose we do that               NaN
2  @sprintcare I have sent several private messag...                 1
3  @115712 Please send us a Private Message so th...                 3
4                                 @sprintcare I did.                 4

   in_response_to_tweet_id
0                      3.0
1                      1.0
2                      4.0
3                      5.0
4                      6.0

In [5]:
df["author_id"] = df["author_id"].astype(str)

companies = df[
    ~df["author_id"].str.match(r"^\d+$")
]["author_id"].unique()

print("Number of companies:", len(companies))
print(companies)

#explore the dataset to list the distinct companies

Number of companies: 108
<StringArray>
[     'sprintcare',    'Ask_Spectrum',  'VerizonSupport',  'ChipotleTweets',
  'AskPlayStation', 'marksandspencer',  'MicrosoftHelps',      'ATVIAssist',
       'AdobeCare',      'AmazonHelp',
 ...
 'mediatemplehelp',       'AskTigogh',  'PandoraSupport',         'askvisa',
      'OPPOCareIN', 'ask_progressive',  'PearsonSupport',         'CarlsJr',
  'HotelTonightCX',    'KeyBank_Help']
Length: 108, dtype: str

In [6]:
company_counts = (
    df[~df["author_id"].str.match(r"^\d+$")]
    ["author_id"]
    .value_counts()
)

print(company_counts)

# check which company has the highest amount of tweets

author_id
AmazonHelp        169840
AppleSupport      106860
Uber_Support       56270
SpotifyCares       43265
Delta              42253
                   ...
JackBox              266
OfficeSupport        218
AskDSC               210
CarlsJr              196
HotelTonightCX       152
Name: count, Length: 108, dtype: int64

In [7]:
amazon_df = df[
    (df["author_id"] == "AmazonHelp") |
    (df["text"].str.contains("@AmazonHelp", case=False, na=False))
]

# filtering the dataset

In [8]:
print(amazon_df.head())
print("Number of tweets:", len(amazon_df))

     tweet_id   author_id  inbound                      created_at  \
181       269  AmazonHelp    False  Wed Nov 22 09:23:01 +0000 2017
182       270      115770     True  Wed Nov 22 09:24:30 +0000 2017
183       271      115770     True  Wed Nov 22 09:30:36 +0000 2017
184       273  AmazonHelp    False  Wed Nov 22 09:40:27 +0000 2017
185       274      115770     True  Wed Nov 22 09:44:04 +0000 2017

                                                  text response_tweet_id  \
181  @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは...           270,271
182      @AmazonHelp ありがとうございます。\n今、電話で主人が対応していただいてます。               NaN
183  @AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎ...               273
184  @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました...               274
185                      @AmazonHelp こちらこそありがとうございました。               275

     in_response_to_tweet_id
181                    272.0
182                    269.0
183                    269.0
184                    271.0
185                    273.0
Number of tweets: 305008

In [9]:
# understanding the dataset

print("Rows:", amazon_df.shape[0])
print("Columns:", amazon_df.shape[1])

Rows: 305008
Columns: 7

In [10]:
missing = pd.DataFrame({
    "Missing Count": amazon_df.isnull().sum(),
    "Missing %": amazon_df.isnull().mean() * 100
})

print(missing)

                         Missing Count  Missing %
tweet_id                             0   0.000000
author_id                            0   0.000000
inbound                              0   0.000000
created_at                           0   0.000000
text                                 0   0.000000
response_tweet_id               119543  39.193398
in_response_to_tweet_id          22907   7.510295

In [11]:
customer_tweets = amazon_df[amazon_df["inbound"] == True]

In [12]:
answered = customer_tweets["response_tweet_id"].notna().sum()
unanswered = customer_tweets["response_tweet_id"].isna().sum()

print("Answered:", answered)
print("Unanswered:", unanswered)

Answered: 100187
Unanswered: 34973

In [13]:
print(amazon_df.head())

     tweet_id   author_id  inbound                      created_at  \
181       269  AmazonHelp    False  Wed Nov 22 09:23:01 +0000 2017
182       270      115770     True  Wed Nov 22 09:24:30 +0000 2017
183       271      115770     True  Wed Nov 22 09:30:36 +0000 2017
184       273  AmazonHelp    False  Wed Nov 22 09:40:27 +0000 2017
185       274      115770     True  Wed Nov 22 09:44:04 +0000 2017

                                                  text response_tweet_id  \
181  @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは...           270,271
182      @AmazonHelp ありがとうございます。\n今、電話で主人が対応していただいてます。               NaN
183  @AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎ...               273
184  @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました...               274
185                      @AmazonHelp こちらこそありがとうございました。               275

     in_response_to_tweet_id
181                    272.0
182                    269.0
183                    269.0
184                    271.0
185                    273.0

In [14]:
#cleaning the amazon dataset 

amazon_df["created_at"] = pd.to_datetime(
    amazon_df["created_at"]
)

/tmp/ipykernel_24961/2736087902.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  amazon_df["created_at"] = pd.to_datetime(

In [15]:
amazon_df["is_reply"] = amazon_df["in_response_to_tweet_id"].notna()

amazon_df["has_response"] = amazon_df["response_tweet_id"].notna()

In [16]:
print("Duplicate rows:", amazon_df.duplicated().sum())
print("Duplicate tweet IDs:", amazon_df["tweet_id"].duplicated().sum())

Duplicate rows: 0
Duplicate tweet IDs: 0

In [17]:
amazon_df["created_at"] = pd.to_datetime(
    amazon_df["created_at"],
    utc=True
)

In [18]:
print(amazon_df["created_at"].dtype)

datetime64[us, UTC]

In [19]:
amazon_df["clean_text"] = (
    amazon_df["text"]
    .str.replace(r"http\S+|www\S+", "", regex=True)
    .str.replace(r"@\w+", "", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [20]:
customer_df = amazon_df[
    amazon_df["inbound"] == True
].copy()

amazon_response_df = amazon_df[
    amazon_df["inbound"] == False
].copy()

print("Customer messages:", len(customer_df))
print("Amazon messages:", len(amazon_response_df))

Customer messages: 135160
Amazon messages: 169848

In [21]:
print(amazon_df.head())

     tweet_id   author_id  inbound                created_at  \
181       269  AmazonHelp    False 2017-11-22 09:23:01+00:00
182       270      115770     True 2017-11-22 09:24:30+00:00
183       271      115770     True 2017-11-22 09:30:36+00:00
184       273  AmazonHelp    False 2017-11-22 09:40:27+00:00
185       274      115770     True 2017-11-22 09:44:04+00:00

                                                  text response_tweet_id  \
181  @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは...           270,271
182      @AmazonHelp ありがとうございます。\n今、電話で主人が対応していただいてます。               NaN
183  @AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎ...               273
184  @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました...               274
185                      @AmazonHelp こちらこそありがとうございました。               275

     in_response_to_tweet_id  is_reply  has_response  \
181                    272.0      True          True
182                    269.0      True         False
183                    269.0      True          True
184                    271.0      True          True
185                    273.0      True          True

                                            clean_text
181  こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況...
182                   ありがとうございます。 今、電話で主人が対応していただいてます。
183  電話で対応してもらいましたが改良されませんでした。 保証期間も過ぎてるので買い直しになるんで...
184  カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただ...
185                                  こちらこそありがとうございました。

In [22]:
amazon_df["text_length"] = amazon_df["clean_text"].str.len()

In [23]:
amazon_df[amazon_df["text_length"] < 5][
    ["tweet_id", "text", "clean_text"]
].head(20)

       tweet_id                                          text clean_text
3872       5310                              @AmazonHelp Yes.       Yes.
7506      11032                               @AmazonHelp Yes        Yes
7552      11076   @118088 @AmazonHelp https://t.co/JeO1QDroxC
9801      13565          @AmazonHelp https://t.co/saX0kAZVCW!
10131     13917          @AmazonHelp  https://t.co/DJzdya8ZMM
12751     16877  @AmazonHelp @119704  https://t.co/rUjHdeMm9G
14419     18729          @AmazonHelp  https://t.co/LzRfyE5m3q
14618     18919          @AmazonHelp  https://t.co/9QpAMYZbaJ
14783     19109                                   @AmazonHelp
15080     19468                              @AmazonHelp .com       .com
16496     21399                              @AmazonHelp *ihr       *ihr
16629     21563          @AmazonHelp  https://t.co/RhLDADmDNX
16884     21850                              @AmazonHelp Oh 🙄       Oh 🙄
17418     22498           @AmazonHelp https://t.co/SGdJV5T2f4
17422     22502           @AmazonHelp https://t.co/QCt7kMtESE
17478     22561                                @AmazonHelp no         no
17479     22563          @AmazonHelp  https://t.co/HWXuUYZUsi
18773     24475                               @AmazonHelp Grt        Grt
18827     24532                               @AmazonHelp Yes        Yes
18831     24537                               @AmazonHelp Yes        Yes

In [24]:
print(amazon_df["inbound"].value_counts())

print("\nAuthor distribution:")
print(amazon_df["author_id"].value_counts().head(20))

inbound
False    169848
True     135160
Name: count, dtype: int64

Author distribution:
author_id
AmazonHelp    169840
169172           447
326613           162
469296           112
158494           101
177530            96
270757            79
182606            73
147113            71
130878            71
360103            69
216871            66
120538            65
219482            65
159034            64
164808            64
366269            64
158284            62
322303            59
167356            57
Name: count, dtype: int64

In [25]:
print("\nAmazon tweets:")
print((amazon_df["author_id"] == "AmazonHelp").sum())

print("\nCustomer tweets:")
print((amazon_df["inbound"] == True).sum())

Amazon tweets:
169840

Customer tweets:
135160

In [26]:
amazon_messages = amazon_df[
    (amazon_df["author_id"] == "AmazonHelp") &
    (amazon_df["inbound"] == False)
].copy()

print("Amazon messages:", len(amazon_messages))

print(
    "Amazon messages with parent:",
    amazon_messages["in_response_to_tweet_id"].notna().sum()
)

print(
    "Amazon messages without parent:",
    amazon_messages["in_response_to_tweet_id"].isna().sum()
)

Amazon messages: 169840
Amazon messages with parent: 169287
Amazon messages without parent: 553

In [27]:
amazon_messages = amazon_messages.rename(
    columns={
        "tweet_id": "amazon_tweet_id",
        "in_response_to_tweet_id": "customer_tweet_id",
        "created_at": "amazon_time",
        "text": "amazon_response",
        "clean_text": "clean_amazon_response"
    }
)

In [28]:
customer_messages = amazon_df[
    amazon_df["inbound"] == True
].copy()

customer_messages = customer_messages.rename(
    columns={
        "tweet_id": "customer_tweet_id",
        "author_id": "customer_id",
        "created_at": "customer_time",
        "text": "customer_query",
        "clean_text": "clean_customer_query"
    }
)

In [29]:
conversation_df = amazon_messages.merge(
    customer_messages,
    on="customer_tweet_id",
    how="inner"
)

In [30]:
print(conversation_df.head())

   amazon_tweet_id   author_id  inbound_x               amazon_time  \
0              273  AmazonHelp      False 2017-11-22 09:40:27+00:00
1              275  AmazonHelp      False 2017-11-22 10:06:26+00:00
2              618  AmazonHelp      False 2017-10-31 23:28:00+00:00
3              625  AmazonHelp      False 2017-10-31 22:34:32+00:00
4              629  AmazonHelp      False 2017-11-01 12:53:34+00:00

                                     amazon_response response_tweet_id_x  \
0  @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました...                 274
1  @115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお...                 NaN
2  @115820 We'd like to take a further look into ...                 619
3  @115824 Wir haben zu danken. Schönen Abend noc...                 NaN
4              @115827 Thanks for your patience. ^KM                 NaN

   customer_tweet_id  is_reply_x  has_response_x  \
0              271.0        True            True
1              274.0        True           False
2              616.0        True            True
3              623.0        True           False
4              627.0        True           False

                               clean_amazon_response  ...  customer_id  \
0  カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただ...  ...       115770
1     恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET  ...       115770
2  We'd like to take a further look into this wit...  ...       115820
3       Wir haben zu danken. Schönen Abend noch. ^JS  ...       115824
4                      Thanks for your patience. ^KM  ...       115827

  inbound_y             customer_time  \
0      True 2017-11-22 09:30:36+00:00
1      True 2017-11-22 09:44:04+00:00
2      True 2017-10-31 23:22:08+00:00
3      True 2017-10-31 22:32:07+00:00
4      True 2017-11-01 12:50:18+00:00

                                      customer_query response_tweet_id_y  \
0  @AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎ...                 273
1                      @AmazonHelp こちらこそありがとうございました。                 275
2  @AmazonHelp 3 different people have given 3 di...                 618
3               @AmazonHelp Okay, danke für die Info                 625
4  @AmazonHelp @115826 Yeah this is crazy we’re l...                 629

  in_response_to_tweet_id  is_reply_y  has_response_y  \
0                   269.0        True            True
1                   273.0        True            True
2                   615.0        True            True
3                   622.0        True            True
4                   626.0        True            True

                                clean_customer_query text_length_y
0  電話で対応してもらいましたが改良されませんでした。 保証期間も過ぎてるので買い直しになるんで...            51
1                                  こちらこそありがとうございました。            17
2  3 different people have given 3 different answ...           135
3                           Okay, danke für die Info            24
4  Yeah this is crazy we’re less than a week away...           128

[5 rows x 21 columns]

In [31]:
conversation_df["response_time"] = (
    conversation_df["amazon_time"]
    - conversation_df["customer_time"]
)

In [32]:
print(
    conversation_df[
        [
            "customer_tweet_id",
            "customer_query",
            "amazon_tweet_id",
            "amazon_response",
            "response_time"
        ]
    ].head(10)
)

   customer_tweet_id                                     customer_query  \
0              271.0  @AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎ...
1              274.0                      @AmazonHelp こちらこそありがとうございました。
2              616.0  @AmazonHelp 3 different people have given 3 di...
3              623.0               @AmazonHelp Okay, danke für die Info
4              627.0  @AmazonHelp @115826 Yeah this is crazy we’re l...
5              634.0  @115821 @AmazonHelp why is my order at my loca...
6              638.0                 @AmazonHelp Hi ready for some help
7              640.0  @AmazonHelp Is the Echo Show no longer supported?
8              643.0  Bought an @115821 Echo Show and it won’t recog...
9              646.0  .@AmazonHelp Item has not been delivered but t...

   amazon_tweet_id                                    amazon_response  \
0              273  @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました...
1              275  @115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお...
2              618  @115820 We'd like to take a further look into ...
3              625  @115824 Wir haben zu danken. Schönen Abend noc...
4              629              @115827 Thanks for your patience. ^KM
5              633  @115831 I'm sorry for the wait. Please reach o...
6              637  @115834 Were you able to reach us at the link ...
7              639  @115834 The Echo Show is supported, please rea...
8              642  @115834 Oh no, I'm sorry for the issues! For t...
9              644  @115835 I'm so sorry you didn't receive your p...

    response_time
0 0 days 00:09:51
1 0 days 00:22:22
2 0 days 00:05:52
3 0 days 00:02:25
4 0 days 00:03:16
5 0 days 00:46:39
6 0 days 00:06:11
7 0 days 00:06:34
8 0 days 01:07:54
9 0 days 00:44:57

In [36]:
print(
    "Empty customer queries:",
    (conversation_df["clean_customer_query"].fillna("").str.strip() == "").sum()
)

print(
    "Empty Amazon responses:",
    (conversation_df["clean_amazon_response"].fillna("").str.strip() == "").sum()
)

Empty customer queries: 1178
Empty Amazon responses: 9

In [39]:
empty_customer = conversation_df[
    conversation_df["clean_customer_query"].fillna("").str.strip() == ""
]

print(empty_customer[
    ["customer_tweet_id", "customer_query", "clean_customer_query",
     "amazon_response"]
].head(30))

      customer_tweet_id                                     customer_query  \
249             13565.0               @AmazonHelp https://t.co/saX0kAZVCW!
383             16877.0       @AmazonHelp @119704  https://t.co/rUjHdeMm9G
519             18729.0               @AmazonHelp  https://t.co/LzRfyE5m3q
554             19109.0                                        @AmazonHelp
788             22502.0                @AmazonHelp https://t.co/QCt7kMtESE
805             22563.0               @AmazonHelp  https://t.co/HWXuUYZUsi
898             25291.0               @AmazonHelp  https://t.co/1dmMd2wSOv
1097            29946.0               @AmazonHelp  https://t.co/b5RacHAicP
1344            36503.0                @AmazonHelp https://t.co/eNaIWKNoXP
1353            36525.0               @AmazonHelp  https://t.co/o5Bh0mjaDF
1419            38138.0                                        @AmazonHelp
1569            43736.0                @AmazonHelp https://t.co/gu1CLsiExC
1656            47917.0                                @115821 @AmazonHelp
1787            52949.0                                @115830 @AmazonHelp
1788            52952.0               @AmazonHelp  https://t.co/J9lOuO5jIQ
1924            59575.0                @AmazonHelp https://t.co/eny26p6KKa
1925            59575.0                @AmazonHelp https://t.co/eny26p6KKa
1934            60239.0               @AmazonHelp  https://t.co/RgXjQzVzpI
2199            65762.0               @AmazonHelp  https://t.co/1P0u4Qd6HE
2345            69753.0               @AmazonHelp  https://t.co/yIyAxTqMl7
2346            69756.0               @AmazonHelp  https://t.co/ayGD2MEsYw
2631            74824.0               @AmazonHelp  https://t.co/A14wLE2Asi
2797            77533.0                @AmazonHelp https://t.co/u2pSfScoie
2896            80569.0               @AmazonHelp  https://t.co/zT0zqohrWQ
3306            93477.0               @AmazonHelp  https://t.co/7xbk7GK8o4
3398            95357.0               @AmazonHelp  https://t.co/rOf6OglFvp
3452            96716.0               @AmazonHelp  https://t.co/bKCgsiJ2W8
3457            96716.0               @AmazonHelp  https://t.co/bKCgsiJ2W8
3528            98704.0  @116928 @AmazonHelp @135806 https://t.co/DtzPX...
3554            99794.0  @AmazonHelp @115851 @118702 @122599 @122951 @1...

     clean_customer_query                                    amazon_response
249                        @118829 Can you confirm the delivery date prov...
383                        @119703 However, you need to adhere to guideli...
519                        @120177 Thanks for the information! Who is the...
554                                              @120259 Hey, what's up? ^AS
788                        @120918 Hi, have you been in touch with the pu...
805                        @120930 We'd like to take another look into th...
898                        @121470 It appears the item is set to arrive t...
1097                       @122588 Please provide a few more details and ...
1344                       @123962 Thanks for sharing! Do you currently h...
1353                       @123963 Apologies, please respond to the email...
1419                       @124281 Hi, what delivery date is listed in yo...
1569                       @125706 What were you advised from our email r...
1656                       @126716 If you're sending a surprise and need ...
1787                       @127925 So sorry about that! We would like to ...
1788                       @127926 En este caso te sugiero contactar a nu...
1924                       @129590 As for the order, please keep us updat...
1925                       @129590 For your security, please remove the l...
1934                       @129772 To clarify, is this the same error you...
2199                       @131042 Hi, is the white one refurbished or ne...
2345                       @131801 Oje, da ist wohl etwas schief gegangen...
2346                       @131801 Hey Sascha, natürlich kann ich versteh...
2631                       @132745 Could you please confirm if you've res...
2797                       @133264 Hi, really sorry to hear this has happ...
2896                       @116058 Thanks for the information, Travis! My...
3306                       @136257 Gracias por la información, Misael. Po...
3398                       @136736 Dina, ¿nos podrías indicar si este ped...
3452                       @137106 Please keep us informed of your delive...
3457                       @137106 I'm very sorry that you've had this fr...
3528                       @137604 Hola Gonzalo. Lamentamos las molestias...
3554                       @137847 Sorry for the hassle, Ashoni. We'd lik...

In [40]:
empty_amazon = conversation_df[
    conversation_df["clean_amazon_response"].fillna("").str.strip() == ""
]

print(empty_amazon[
    ["customer_tweet_id", "customer_query",
     "amazon_tweet_id", "amazon_response",
     "clean_amazon_response"]
].head(20))

       customer_tweet_id                                     customer_query  \
3055             83562.0  @AmazonHelp Fatto! Grazie mille. Siete stati m...
5473            141089.0  @AmazonHelp moi je vois toujours la même chose...
9292            229778.0                         @AmazonHelp ça en fera 6 ♥
13903           313278.0  @AmazonHelp Sans vous oublier l'aide en ligne ...
23187           473301.0  @AmazonHelp Je le zyeutais depuis un moment et...
29435           644764.0  @AmazonHelp Échec. Je ne trouve rien qui me pe...
79934          2343905.0  @AmazonHelp I've got parental controls on but ...
80120          2349633.0  @AmazonHelp No vabeh, siete fantastici. Avete ...
94501          2835575.0   @AmazonHelp Nö 😂😂 Aver vllt eurem Lieferanten :D

       amazon_tweet_id                  amazon_response clean_amazon_response
3055             83563  @134353 https://t.co/U1UwrOgNWU
5473            141091  @147823 https://t.co/omIzwlmnZt
9292            229779  @170759 https://t.co/STqZg0HrrN
13903           313279  @190809 https://t.co/z0tRSP2D75
23187           473303  @227701 https://t.co/QjZosZmQJQ
29435           644766  @273031 https://t.co/kstwpDVkpD
79934          2343907  @677876 https://t.co/4DErCqzO2I
80120          2349635  @679157 https://t.co/lAilTN5Txn
94501          2835577                          @131789

In [38]:
conversation_df["customer_length"] = (
    conversation_df["clean_customer_query"]
    .str.len()
)

conversation_df[
    conversation_df["customer_length"] < 10
][
    [
        "customer_query",
        "amazon_response",
        "customer_length"
    ]
].head(30)

,customer_query,amazon_response,customer_length
71,@AmazonHelp Sadly yes,@116617 What devices are you using for Amazon ...,9
103,@AmazonHelp Yes.,@116932 Can you tell us when this information ...,4
165,@AmazonHelp Yes,@118079 I hope you are willing to give us a ch...,3
166,@AmazonHelp Yes,@118079 I'm sorry we let you down on this orde...,3
205,@AmazonHelp AMZL US,@117955 Please provide your details here: http...,7
249,@AmazonHelp https://t.co/saX0kAZVCW!,@118829 Can you confirm the delivery date prov...,0
257,@AmazonHelp done.,"@118918 Thank you for letting us know, we'll g...",5
343,@AmazonHelp No..!!,@119700 Request you to check for our response ...,6
383,@AmazonHelp @119704 https://t.co/rUjHdeMm9G,"@119703 However, you need to adhere to guideli...",0
519,@AmazonHelp https://t.co/LzRfyE5m3q,@120177 Thanks for the information! Who is the...,0
554,@AmazonHelp,"@120259 Hey, what's up? ^AS",0
586,@AmazonHelp .com,"@120322 Apologies, have you looked into fillin...",4
616,@AmazonHelp i have :),"@120463 ok, and were you given some informatio...",9
645,@AmazonHelp How soon?,@120613 Please allow us 6-12 hours to get back...,9
788,@AmazonHelp https://t.co/QCt7kMtESE,"@120918 Hi, have you been in touch with the pu...",0
805,@AmazonHelp https://t.co/HWXuUYZUsi,@120930 We'd like to take another look into th...,0
836,@AmazonHelp Yeah!,"@121156 Hmmm, odd! Please use this link to pro...",5
854,@AmazonHelp Yes,@121290 May I please know what error do you se...,3
856,@AmazonHelp Yes,@121290 Kindly contact our team here: https://...,3
866,@AmazonHelp Done,@121399 Thanks for sharing your details with u...,4
891,@AmazonHelp Yeah,@121460 Have they responded back to you ? We d...,4
898,@AmazonHelp https://t.co/1dmMd2wSOv,@121470 It appears the item is set to arrive t...,0
947,@AmazonHelp Delivered,@121666 Oh no! Have you tried these steps to l...,9
1010,@AmazonHelp 30th,@122105 And does it advise anything on the tra...,4
1065,@AmazonHelp Yes,@122371 You may check it out here: https://t.c...,3
1097,@AmazonHelp https://t.co/b5RacHAicP,@122588 Please provide a few more details and ...,0
1099,@AmazonHelp Sent.,"@122588 We just received the form, Heather! So...",5
1100,@AmazonHelp thx 👍,@122589 Gerne! ^DW,5
1150,@AmazonHelp Alright g,"@122723 Glad to help, have a great day! 😊 - Ta...",9
1157,@AmazonHelp How soon,"@120032 As we're working on this, we'll be sur...",8